#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the ogva network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xc0,0xa8,0x64,0x56,0x9c,0xb0,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xc0,0xa8,0x64,0x56,0xa0,0x98,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
